### ISSUE TITLE
Post Reponse

### ISSUE THREAD

**Issue by rossedman** [drupol/Taleo#2]
First off, thank you so much for building this. I can't say how crazy looking over the documentation for this API has made me.

I am having problems posting a candidate to Taleo. I am not very familiar with the actual software itself. I can connect, I can query candidates and get responses so I know I am in the ballpark. Just using the examples I have not been able to create a candidate though.

Any ideas?

**Comment by drupol** [comment]
Hi,

Did you succeeded to do it using the demo file ?

Thanks!

**Comment by rossedman** [comment]
I tried using the demo and it did not work. But the query, put and delete did work for me. I tried to create a new candidate and it did not work.

**Comment by drupol** [comment]
Do you have the permissions to do it in Taleo ?
Do you have any logs that might be useful ? 

thx!

**Comment by rossedman** [comment]
I can't get the logs working and I do have permissions because I am able to update, delete and query through the methods provided.

**Comment by rossedman** [comment]
Is there a place to check these permission in Taleo? Could I have permissions to do these other things without having the permissions to create new candidates?

**Comment by drupol** [comment]
Why can't you have Taleo logs working ?
Have you tried with:

```
$taleo->loglevel(\Monolog\Logger::DEBUG, 'php://stdout');
```

?

**Comment by rossedman** [comment]
I did. I am using MAMP and I cannot find where the log is outputting. Do you know where it would be output? Thanks for all your help.

**Comment by rossedman** [comment]
We could never find where the log was posting too. Seems like it never created a log. However, Taleo was having problems with country code we were posting. This was the hang up.

**Comment by drupol** [comment]
Cool, I'm glad you find a solution, don't hesitate to add some example code to help others, I'll include it in the demo file!

Bye.
