### ISSUE TITLE
api Taleo authentification candidate

### ISSUE THREAD

**Issue by nicosolo** [drupol/Taleo#3]
hi,

I have a questions.
Is it possible to authentification with a candidate in Taleo API?
I can set password but i can not authenticate me as a candidate.
Thanks

Nicolas

**Comment by drupol** [comment]
Hi Nico,

I was about to reply to the mail you sent me, but I will do it here so everyone can see it.

I don't know if it's possible to authenticate candidate, I don't think it's possible yet.
Have you checked the PDF in the documentation section ?

Thanks for your message!

**Comment by nicosolo** [comment]
Hi,
Thanks for your answer.

Yes i have check the pdf but I found nothing on the authentication of a candidate. That's why I contacted you.

Thancks again!
